start/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from required import required
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns('',
  url(r'^admin/', include(admin.site.urls)),
  url(r'^accounts/', include('django.contrib.auth.urls')),
  url(r'^accounts/', include('registration.backends.default.urls')),
)

urlpatterns += required(
  login_required,
  patterns('',
    url(r'^todos/', include('todos.urls', namespace='todos')),
  )
)

todos/urls.py
from django.conf.urls import patterns, url
from todos.views import TodoView

import views

urlpatterns = patterns('',
  url(r'^$', views.today, name='today'),
  url(r'^future$', views.future, name='future'),
  url(r'^fixed$', views.fixed, name='fixed'),
  url(r'^fix$', views.fix, name='fix'),
  url(r'^remove$', views.remove, name='remove'),
  url(r'^new$', TodoView.as_view(), name='new'),
)

todos/models.py
from django.db import models
from django.contrib.auth.models import User

class Todo(models.Model):
  NEW = 0
  FIXED = 1
  STATUSES = (
    (NEW, 'New'),
    (FIXED, 'Fixed')
  )

  user = models.ForeignKey(User)
  name = models.TextField()
  date = models.DateField()
  status = models.PositiveSmallIntegerField(choices=STATUSES, default=NEW)

  def fix(self):
    self.status = self.FIXED
    self.save()

  def __unicode__(self):
    return self.name

start/views.py
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.core.urlresolvers import reverse

def app_logout(request):
  logout(request)
  return redirect(reverse('login'))

todos/views.py
from datetime import date
from todos.models import Todo
from django.db import transaction
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from django.views.decorators.csrf import csrf_protect
from django.core.urlresolvers import reverse


class TodoView(CreateView):
  model = Todo
  fields = ('name', 'date')

  def get_success_url(self):
    return reverse('todos:today')

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super(TodoView, self).form_valid(form)


def today(req):
  todos = Todo.objects.filter(date__lte=date.today(), status=Todo.NEW, user=req.user)
  return render(req, 'todos/today.html', {'todos': todos})


def future(req):
  todos = Todo.objects.filter(date__gt=date.today(), status=Todo.NEW, user=req.user)
  return render(req, 'todos/future.html', {'todos': todos})


def fixed(req):
  todos = Todo.objects.filter(status=Todo.FIXED, user=req.user)
  return render(req, 'todos/fixed.html', {'todos': todos})


@csrf_protect
@transaction.commit_on_success
def fix(req):
  return _process_todos(req, lambda x: x.fix())


@csrf_protect
@transaction.commit_on_success
def remove(req):
  return _process_todos(req, lambda x: x.delete())


def _process_todos(req, command):
 todo_ids = req.POST.getlist('todo_ids')
 map(command, Todo.objects.filter(id__in=todo_ids, user=req.user))
 return redirect(req.META.get('HTTP_REFERER'))

start/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Auth</title>
    {% load staticfiles %}
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  </head>
  <body>
    <div>
      <span><a href="{% url 'login' %}">Login</a></span>
      <span><a href="{% url 'registration_register' %}">Register</a></span>
    </div>
    <hr/>
    {% block content %}{% endblock %}
  </body>
</html>

todos/templates/todos/_list_with_form.html
{% if todos %}
  <form method='POST'>
    {% csrf_token %}
    <ul>
      {% for todo in todos %}
        <li>
          <input type='checkbox' name='todo_ids' value='{{ todo.id }}' />&nbsp;
          {{ todo.name }} {{ todo.date }}
        </li>
      {% endfor %}
    </ul>
  </form>
{% else %}
  <b>The list is empty!</b>
{% endif %}

todos/templates/todos/base/_top_links.html
<div>
  <a href="{% url 'todos:today' %}">Today</a>
  <a href="{% url 'todos:future' %}">Future</a>
  <a href="{% url 'todos:fixed' %}">Fixed</a>
</div>

todos/templates/todos/base/_user.html
<div>
  <span>Hi, {{ user }}!</span>
  <span><a href="{% url 'logout' %}?next={% url 'login' %}">Logout</a></span>
</div>
<hr/>

todos/templates/todos/base/layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo Application</title>
    {% load staticfiles %}
    <script src="{% static 'todos/js/jquery.js' %}"></script>
    <script src="{% static 'todos/js/app.js' %}"></script>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  </head>
  <body>
    {% include 'todos/base/_user.html' %}
    {% include 'todos/base/_top_links.html' %}
    {% block content %}{% endblock %}
  </body>
</html>

todos/templates/todos/feature.html
{% include 'todos/_top_links.html' %}

<h1>Someday todos</h1>

<ul>
  {% for todo in todos %}
    <li>
      {{ todo.name }} {{ todo.date }}
    </li>
  {% endfor %}
</ul>

todos/templates/todos/fixed.html
{% extends 'todos/base/layout.html' %}

{% block content %}
  <h1>Fixed todos</h1>

  {% include 'todos/_list_with_form.html' %}

  <div class='form-actions'>
  <a href="{% url 'todos:new' %}">Add task</a>
    {% if todos %}
      <a href="{% url 'todos:remove' %}" class='action-link'>Remove</a>
    {% endif %}
  </div>
{% endblock %}

todos/templates/todos/future.html
{% extends 'todos/base/layout.html' %}

{% block content %}
  <h1>Future todos</h1>

  {% include 'todos/_list_with_form.html' %}

  <div class='form-actions'>
  <a href="{% url 'todos:new' %}">Add task</a>
    {% if todos %}
      <a href="{% url 'todos:fix' %}" class='action-link'>Fix</a>
      <a href="{% url 'todos:remove' %}" class='action-link'>Remove</a>
    {% endif %}
  </div>
{% endblock %}

todos/templates/todos/layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo Application</title>
    {% load staticfiles %}
    <script src="{% static 'todos/js/jquery.js' %}"></script>
    <script src="{% static 'todos/js/app.js' %}"></script>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  </head>
  <body>
    {% include 'todos/_top_links.html' %}
    {% block content %}{% endblock %}
  </body>
</html>

todos/templates/todos/today.html
{% extends 'todos/base/layout.html' %}

{% block content %}
  <h1>Today todos</h1>

  {% include 'todos/_list_with_form.html' %}

  <div class='form-actions'>
    <a href="{% url 'todos:new' %}">Add task</a>
    {% if todos %}
      <a href="{% url 'todos:fix' %}" class='action-link'>Fix</a>
      <a href="{% url 'todos:remove' %}" class='action-link'>Remove</a>
    {% endif %}
  </div>
{% endblock %}

todos/templates/todos/todo_form.html
{% extends 'todos/base/layout.html' %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
  </form>
{% endblock %}